openapi: 3.0.0
servers: 
  - url: /
    description: Main server
info:
  description: Manito API
  version: "1.0"
  title: Manito API
  contact:
    email: b.nagy.balint@gmail.com
paths:
  /version:
    get:
      summary: Returns version information about the service
      operationId: endpoint.get_version.get_version
      responses:
        "200":
          description: Version information
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/VersionInfo"
  /users:
    get:
      summary: Lists all users
      operationId: endpoint.get_users.get_users
      tags:
        - user
      responses:
        "200":
          description: List of users
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: "#/components/schemas/User"
  /user/{user_id}:
    get:
      summary: Returns detailed information about a user
      operationId: endpoint.get_user.get_user
      tags:
        - user
      parameters:
        - name: user_id
          in: path
          required: true
          schema:
            type: integer
      responses:
        "200":
          description: User details
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: "#/components/schemas/User"
        "404":
          description: User does not exist
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/BasicError"
  /user/{user_id}/wallets:
    get:
      summary: Lists wallets of a user
      operationId: endpoint.get_user_wallets.get_user_wallets
      tags:
        - user
        - wallet
      parameters:
        - name: user_id
          in: path
          required: true
          schema:
            type: integer
      responses:
        "200":
          description: List of wallets
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Wallet"
        "404":
          description: User does not exist
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/BasicError"
  /user/{user_id}/categories:
    get:
      summary: Lists transaction categories of a user
      operationId: endpoint.get_user_categories.get_user_categories
      tags:
        - user
        - category
      parameters:
        - name: user_id
          in: path
          required: true
          schema:
            type: integer
      responses:
        "200":
          description: List of categories
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Category"
        "404":
          description: User does not exist
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/BasicError"
  /wallet/{wallet_id}:
    get:
      summary: Returns detailed information about a wallet
      operationId: endpoint.get_wallet.get_wallet
      tags:
        - wallet
      parameters:
        - name: wallet_id
          in: path
          required: true
          schema:
            type: integer
      responses:
        "200":
          description: Wallet details
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Wallet"
        "404":
          description: Wallet does not exist
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/BasicError"
  /wallet/{wallet_id}/transactions:
    get:
      summary: Lists transactions for a wallet
      operationId: endpoint.get_wallet_transactions.get_wallet_transactions
      deprecated: true
      tags:
        - wallet
        - transaction
      parameters:
        - name: wallet_id
          in: path
          required: true
          schema:
            type: integer
        - name: from_date
          in: query
          required: false
          schema:
            description: Start date of the search, inclusive. Time is interpreted in the wallet's time settings.
            type: string
            format: date
        - name: to_date
          in: query
          required: false
          schema:
            description: End date of the search, inclusive. Time is interpreted in the wallet's time settings.
            type: string
            format: date
      responses:
        "200":
          description: List of transactions
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: "#/components/schemas/Transaction"
        "404":
          description: Wallet does not exist
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/BasicError"
  /transaction/{transaction_id}:
    get:
      summary: Returns detailed information about a transaction
      operationId: endpoint.get_transaction.get_transaction
      tags:
        - transaction
      parameters:
        - name: transaction_id
          in: path
          required: true
          schema:
            type: integer
      responses:
        "200":
          description: Transaction details
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Transaction"
        "403":
          description: The request was rejected due to authorization issues.
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/BasicError"
        "404":
          description: Transaction does not exist
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/BasicError"
    delete:
      summary: Delete a transaction
      operationId: endpoint.delete_transaction.delete_transaction
      tags:
        - transaction
      parameters:
        - name: transaction_id
          in: path
          required: true
          schema:
            type: integer
      responses:
        "204":
          description: Successfully deleted
        "403":
          description: The request was rejected due to authorization issues.
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/BasicError"
        "404":
          description: Transaction does not exist
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/BasicError"
  /transaction/search:
    post:
      summary: Returns a filtered list of transactions 
      operationId: endpoint.post_transaction_search.post_transaction_search
      tags:
        - transaction
      requestBody:
        description: Filter criteria
        required: true
        content: 
          'application/json':
            schema:
              $ref: "#/components/schemas/TransactionSearchParams"
      responses:
        "200":
          description: List of transactions matching the criteria
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: "#/components/schemas/Transaction"
        "403":
          description: |
            The request was rejected because the filter expression could potentially return information
            that the caller is not authorized for.
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/BasicError"
  /transaction/create:
    post:
      summary: Creates a new transaction
      operationId: endpoint.post_transaction_create.post_transaction_create
      tags:
        - transaction
      requestBody:
        description: Transaction data
        required: true
        content: 
          'application/json':
            schema:
              $ref: "#/components/schemas/Transaction"
      responses:
        "200":
          description: Details of the newly created transaction.
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Transaction"
        "403":
          description: The request was rejected due to authorization issues.
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/BasicError"
  /category/create:
    post:
      summary: Creates a new category
      operationId: endpoint.post_category_create.post_category_create
      tags:
        - category
      requestBody:
        description: Category data
        required: true
        content: 
          'application/json':
            schema:
              $ref: "#/components/schemas/Category"
      responses:
        "200":
          description: Details of the newly created category.
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Category"
        "403":
          description: The request was rejected due to authorization issues.
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/BasicError"
  /category/{category_id}:
    delete:
      summary: Delete a category
      operationId: endpoint.delete_category.delete_category
      tags:
        - category
      parameters:
        - name: category_id
          in: path
          required: true
          schema:
            type: integer
      responses:
        "204":
          description: Successfully deleted
        "403":
          description: The request was rejected due to authorization issues.
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/BasicError"
        "404":
          description: Category does not exist
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/BasicError"


  
components:
  schemas:
    VersionInfo:
      type: object
      description: Version information about the service
      properties:
        version:
          type: string
          example: 1.2.34
      required:
        - version
    DatabaseId:
      type: integer
      description: Database ID
      example: 528491
    User:
      type: object
      description: Information about a user
      properties:
        id:
          allOf:
            - $ref: "#/components/schemas/DatabaseId"
            - description: ID of the user.
        name:
          type: string
          description: Name of the user.
          example: Some Body
        created_at:
          type: string
          description: Time when the user account was created.
          format: date-time
        deleted_at:
          type: string
          description: Time when the user account was deleted.
          format: date-time
      required:
        - id
        - name
        - created_at
    Wallet:
      type: object
      properties:
        id:
          allOf:
            - $ref: "#/components/schemas/DatabaseId"
            - description: ID of this wallet
        name:
          type: string
          description: Name of the wallet
          example: Bank Account at Shady & Co. Banking Trust
        ownerId:
          allOf:
            - $ref: "#/components/schemas/DatabaseId"
            - description: ID of the user who owns this wallet
        createdAt:
          type: string
          format: date-time
          readOnly: true
          description: UTC time when the wallet was created.
      required:
        - id
        - name
        - ownerId
    Category:
      type: object
      properties:
        id:
          allOf:
            - $ref: "#/components/schemas/DatabaseId"
            - description: ID of this category
          readOnly: true
        name:
          type: string
          description: Name of the category
          example: Bills
        ownerId:
          allOf:
            - $ref: "#/components/schemas/DatabaseId"
            - description: ID of the user who owns this category
    Transaction:
      type: object
      properties:
        id:
          allOf:
            - $ref: "#/components/schemas/DatabaseId"
            - description: ID of this wallet
          readOnly: true
        description:
          type: string
          description: Notes on this transaction
        time:
          type: string
          format: date-time
          description: UTC time when the transaction took place.
        amount:
          type: number
          description: |
            Amount of money added to the destination wallet and removed from the source wallet and
            deposited into the destination wallet.
        categoryId:
          allOf:
            - $ref: "#/components/schemas/DatabaseId"
            - description: ID of the category to assign the transaction to.
        sourceWalletId:
          allOf:
            - $ref: "#/components/schemas/DatabaseId"
            - description: |
                ID of the source wallet. If missing, the transaction is considered to be a deposit
                into the destination wallet from the outside world i.e. outside any of the user's wallets
                within the system.
        destinationWalletId:
          allOf:
            - $ref: "#/components/schemas/DatabaseId"
            - description: |
                ID of the destination wallet. If missing, the transaction is considered to be a withdrawal
                from the source wallet to the outside world i.e. outside any of the user's wallets
                within the system.
        createdAt:
          type: string
          format: date-time
          readOnly: true
          description: |
            UTC time when the transaction database entity was created. This may be different from the time
            when the transaction took place, which is stored in the field 'time'.
        deletedAt:
          type: string
          format: date-time
          readOnly: true
          description: UTC time when the transaction database entity was deleted.
      required:
        - id
        - amount
        - time
        - categoryId
        - createdAt
    TransactionSearchParams:
      type: object
      properties:
        walletId:
          allOf:
            - $ref: "#/components/schemas/DatabaseId"
            - description: |
                Result will only contain transactions for which either the source or the destination wallet's ID
                matches this ID.
        searchString:
          type: string
          description: |
            Result will only contain transactions for which the note field contains this string.
            The search is case-insensitive.
        startDate:
          type: string
          format: date
          description: Start of the time range included in the search, including the specified date.
        endDate:
          type: string
          format: date
          description: End of the time range included in the search, including the specified date.
        minAmount:
          type: number
          description: Minimum amount that was transferred with the transaction.
        maxAmount:
          type: number
          description: Maximum amount that was transferred with the transaction.
      additionalProperties: false
    BasicError:
      type: object
      properties:
        message:
          description: Error message
          type: string
      required:
        - message