name: CI
on: [push, pull_request, workflow_dispatch]
jobs:
  unit_tests_python:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v1
    - name: Setup Python
      uses: actions/setup-python@v1
      with:
        python-version: "3.8"
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        python -m pip install -r server/requirements.txt
    - name: Run Python unit tests
      run: |
        python -m pytest server/utest
      env:
        PYTHONPATH: server/
  unit_tests_js:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v1
    - name: Setup Node.js
      uses: actions/setup-node@v1
      with:
        node-version: "16.x"
    - name: Install dependencies
      run: |
        npm install --prefix app/
    - name: Run Javascript unit tests
      run: |
        npm test --prefix app/
