name: CI
on: [push, pull_request]
jobs:
  ut_python:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v1
    - name: Setup Python
      uses: actions/setup-python@v1
      with:
        python-version: "3.8"
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        python -m pip install -r server/requirements.txt
    - name: Run Python unit tests
      run: |
        python -m pytest server/utest
      env:
        PYTHONPATH: server/